zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    account-service:
      path: /info/**
      serviceId: account-service
      stripPrefix: true

server:
  port: 8111

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: routes,filters
  endpoint:
    routes:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
