zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  ignoredServices: '*'
  routes:
    account-service:
      path: /info/**
      serviceId: account-service
      stripPrefix: true

server:
  port: 8111

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30


management:
  endpoints:
    web:
      exposure:
        include: routes,filters
  endpoint:
    routes:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000

