version: "3.7"

services:
  discovery-server:
    image: abninder/discovery
    ports:
      - "8761:8761"
    restart: on-failure
  config-server:
    image: abninder/config-server
    ports:
      - "8888:8888"
    restart: on-failure
  zuul-gateway:
    image: abninder/gateway
    ports:
      - "8111:8111"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
      - hystrix.command.default.execution.timeout.enabled=false
      - zuul.host.connect-timeout-millis=60000
      - zuul.host.socket-timeout-millis=60000
      - ribbon.ReadTimeout=60000
      - ribbon.ConnectTimeout=60000
    depends_on:
      - discovery-server
    restart: on-failure
  accounts-service:
    image: abninder/accounts-api
    ports:
      - "8500:8500"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
      - spring.cloud.config.uri=http://localhost:8888
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
  address-service:
    image: abninder/addresses-api
    ports:
      - "8501:8501"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
      - spring.cloud.config.uri=http://localhost:8888
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
